Taken from [here](https://www.digitalocean.com/community/tutorials/introduction-to-pytorch-build-a-neural-network-to-recognize-handwritten-digits)

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
net = nn.Linear(1, 1)  # 1. Build a computation graph (a line!)
optimizer = optim.SGD(net.parameters(), lr=0.1)  # 2. Setup optimizers
criterion = nn.MSELoss()  # 3. Setup criterion
x, target = torch.randn((1,)), torch.tensor([0.])  # 4. Setup data

In [3]:
net

Linear(in_features=1, out_features=1, bias=True)

In [4]:
x

tensor([-0.1263])

In [5]:
target

tensor([0.])

In [6]:
# 5. Train the model
for i in range(10):
    output = net(x)
    loss = criterion(output, target)
    print(round(loss.item(), 2))

    net.zero_grad()
    loss.backward()
    optimizer.step()

0.34
0.22
0.14
0.09
0.06
0.04
0.02
0.01
0.01
0.01


In [7]:
loss

tensor(0.0057, grad_fn=<MseLossBackward0>)

In [8]:
net

Linear(in_features=1, out_features=1, bias=True)

In [11]:
net.parameters()

<generator object Module.parameters at 0x12d8aca50>

In [13]:
for a in net.named_parameters():
    print(a)

('weight', Parameter containing:
tensor([[-0.8823]], requires_grad=True))
('bias', Parameter containing:
tensor([-0.1715], requires_grad=True))


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from torchvision import datasets, transforms
from torch.optim.lr_scheduler import StepLR

# 1. Build a computation graph
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.fc = nn.Linear(1024, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 1)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        output = F.log_softmax(x, dim=1)
        return output
net = Net()

In [ ]:
datasets.